[package]
name = "bmp-manipulation"
version = "0.1.0"
authors = ["jetstream0"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
